AOSC-Dev/website-2023

index.html
src/pages/home/HomeIndex.vue
src/style.css

this commit moves the backgroud related style attributes to `<body>` to fix it.

fix: backgroud image becomes unstable when scrolling

---

src/pages/home/components/HeaderBar.vue
src/pages/index/components/RightBar.vue
src/utils/utils.js

fix: 修复了主页logo/头图闪动问题

---

index.html
src/App.vue
src/stores/miscellaneous.js
src/style.css

修复季节主题中的背景变化

---

src/pages/download/DownloadIndex.vue

fix(download): 修复安同 OS 及星霞 OS 板块的视觉对齐

---

public/news/2024-09-27-cups-0day-advisory.md
public/news/2024-09-27-cups-0day-advisory.zh-cn.md

feat(news): 添加 CUPS 高危漏洞公告

---

public/news/2024-09-28-aosc-os-set-fcitx5-to-fcitx.md
public/news/2024-09-28-aosc-os-set-fcitx5-to-fcitx.zh-cn.md
public/news/2024-09-28-oma-1.11.0-rc1.md
public/news/2024-09-28-oma-1.11.0-rc1.zh-cn.md

- 2024-09-28-oma-1.11.0-rc1
- 2024-09-28-aosc-os-set-fcitx5-to-fcitx
图片已上传至服务器。
资讯要点：
详情页：

Add-news-2024-09-28

---

public/news/2024-09-28-oma-1.11.0-rc1.md
public/news/2024-09-28-oma-1.11.0-rc1.zh-cn.md
public/news/2024-09-30-oma-1.11.0-rc2.md
public/news/2024-09-30-oma-1.11.0-rc2.zh-cn.md
public/news/2024-09-30-oma-on-apt-2.8.md
public/news/2024-09-30-oma-on-apt-2.8.zh-cn.md
public/news/2024-10-04-oma-1.11.0.md
public/news/2024-10-04-oma-1.11.0.zh-cn.md
public/news/2024-10-06-oma-1.11.0-new-repo-key.md
public/news/2024-10-06-oma-1.11.0-new-repo-key.zh-cn.md
src/pages/download/DownloadIndex.vue

同步 oma 资讯、下载页面新增 deepin/openKylin 安装信息

---

public/news/2024-10-24-condemnation-of-the-linux-foundation-and-its-employees.md
public/news/2024-10-24-condemnation-of-the-linux-foundation-and-its-employees.zh-cn.md

feat(news): add Condemnation of the Linux Foundation and its Employees

---

public/news/2024-10-24-condemnation-of-the-linux-foundation-and-its-employees.md
public/news/2024-10-24-condemnation-of-the-linux-foundation-and-its-employees.zh-cn.md

Fix condemnation links

---

src/pages/events/EventsIndex.vue

feat(events): 更新校园行记录

---

public/news/2024-10-30-aosc-2024-winter-merch-preview.md
public/news/2024-10-30-aosc-2024-winter-merch-preview.zh-cn.md
public/news/2024-11-06-aosc-2024-winter-merch.md
public/news/2024-11-06-aosc-2024-winter-merch.zh-cn.md

- home page
- list page
- detail page

feat(news): add 2024-11-06-aosc-2024-winter-merch

---

public/news/2024-11-21-tailscale-kernel-incompatibility.md
public/news/2024-11-21-tailscale-kernel-incompatibility.zh-cn.md
public/news/2024-12-01-aosc-at-13.md
public/news/2024-12-01-aosc-at-13.zh-cn.md

feat(news): fix news date in 2024-11-21-tailscale-kernel-incompatibility

---

public/news/2024-10-31-oma-1.12.md
public/news/2024-10-31-oma-1.12.zh-cn.md
public/news/2024-12-03-aosc-os-core-12.md
public/news/2024-12-03-aosc-os-core-12.zh-cn.md
public/news/2024-12-08-aosc-sdu-event-vod.md
public/news/2024-12-08-aosc-sdu-event-vod.zh-cn.md
public/news/2024-12-09-aosc-xidian-event-registration.md
public/news/2024-12-09-aosc-xidian-event-registration.zh-cn.md
public/news/2024-12-10-aosc-xidian-event-pre.md
public/news/2024-12-10-aosc-xidian-event-pre.zh-cn.md
public/news/2024-12-16-aosc-xidian-event-vod.md
public/news/2024-12-16-aosc-xidian-event-vod.zh-cn.md
public/news/2024-12-22-aosc-2024-winter-merch.md
public/news/2024-12-22-aosc-2024-winter-merch.zh-cn.md

- home page
- list page
- detail pages

News Updates (Dec. 22, 2024)

---

public/news/2024-12-23-oma-1.13-rc1.md
public/news/2024-12-23-oma-1.13-rc1.zh-cn.md

- home page
- list page 
- detail page

feat(news): add 2024-12-23-oma-1.13-rc1

---

src/pages/home/components/LeftBar.vue

feat(home): move Wiki link up

---

public/news/2024-12-23-oma-1.13-rc1.zh-cn.md
public/news/2024-12-29-oma-1.13.md
public/news/2024-12-29-oma-1.13.zh-cn.md

- home page
- list page
- detail page

feat(news): add 2024-12-29-oma-1.13

---

public/news/2025-01-17-anan-figura-avatar.md
public/news/2025-01-17-anan-figura-avatar.zh-cn.md

- home page
- detail page
- list page

feat(news): add 2025-01-17-anan-figura-avatar

---

public/news/2025-01-22-loonggpu-driver.md
public/news/2025-01-22-loonggpu-driver.zh-cn.md

feat(news): modify graphics performance description

---

index.html

https://ogp.me for more information

feat(index): add Open Graph protocol metadata

---

src/main.js
src/pages/download/DownloadIndex.vue
src/pages/download/components/DownloadButton.vue

feat(download-page): implement 'copy file hash to clipboard' functionality

---

src/pages/download/components/DownloadButton.vue

Actually fixing z-index related problem introduced in 4166212

fix(download): fix mirror select dropdown

---

public/news/2024-12-31-coffee-break.md
public/news/2024-12-31-coffee-break.zh-cn.md
public/news/2025-01-15-rsync-critical-security-update.md
public/news/2025-01-15-rsync-critical-security-update.zh-cn.md
public/news/2025-03-03-coffee-break.md
public/news/2025-03-03-coffee-break.zh-cn.md

- home page
- list page
- detail page

feat(news): add 2025-03-03-coffee-break

---

index.html
src/main.js
src/pages/download/DownloadIndex.vue

feat: april special

---

src/pages/aosc-os/relnote/AoscRelnote.vue

feat(aosc-os/relnote): 更新 2025 年 4 月发行注记

---

public/news/2025-03-10-new-signing-for-apt-repository.md
public/news/2025-03-10-new-signing-for-apt-repository.zh-cn.md
public/news/2025-04-18-aosc-buaa-event-schedule.md
public/news/2025-04-18-aosc-buaa-event-schedule.zh-cn.md
public/news/2025-04-18-migrant-demo.md
public/news/2025-04-18-migrant-demo.zh-cn.md
public/news/2025-04-18-new-signing-for-apt-repository.md
public/news/2025-04-18-new-signing-for-apt-repository.zh-cn.md

- home page
- list page
- detail page

feat: update news

---

package-lock.json
package.json
src/css/code-highlight.scss
src/main.js

feat: 为代码块添加语法高亮

---

src/pages/download/DownloadIndex.vue

fix: stale link in download page

---

.github/workflows/deploy.yaml
nuxt.config.ts

Tested in https://github.com/AOSC-Dev/website-2023/actions/runs/17574420982, verified on server.

chore: update workflow for nuxt

---

src/pages/events/EventsIndex.vue

fix(events): correct Bilibili URL for 2024 Beijing University & TUNA Association event

fix(events): correct Bilibili URL for 2024 Beijing University & TUNA Association event

---

README.md
README.zh-cn.md
nuxt.config.ts

- AOSC-Dev/website-2023-utils#13
- AOSC-Dev/website-2023-config#2

feat: update README files
